//
//  EmotionDetectorStyles.cs
//  EmotionDetector
//
//  Created by Rafael Regh on 14/11/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



using System;
using System.Drawing;
using Foundation;
using UIKit;
using CoreGraphics;

namespace EmotionDetector
{
    [Register ("EmotionDetectorStyles")]
    public class EmotionDetectorStyles : NSObject
    {

        //// Initialization

        static EmotionDetectorStyles()
        {
        }

        //// Drawing Methods

        public static void DrawFaceRect(CGRect frame)
        {

            //// Rectangle Drawing
            var rectanglePath = UIBezierPath.FromRect(new CGRect(frame.GetMinX(), frame.GetMinY(), 90.0f, 90.0f));
            UIColor.Red.SetStroke();
            rectanglePath.LineWidth = 10.0f;
            rectanglePath.Stroke();
        }

    }
}
